CREATE DATABASE [banco]
USE [banco]

CREATE TABLE Perguntas(
ID INT NOT NULL identity,
Corpo VARCHAR(100) NOT NULL,
OpcaoA VARCHAR(50) NOT NULL,
OpcaoB VARCHAR(50) NOT NULL,
OpcaoC VARCHAR(50) NOT NULL,
OpcaoD VARCHAR(50) NOT NULL,
CONSTRAINT pk_Perguntas PRIMARY KEY(ID)
);

CREATE TABLE RespostaDaPergunta
(
ID INT NOT NULL,
Resposta VARCHAR(1) NOT NULL,
CONSTRAINT PK_Resposta PRIMARY KEY(ID),
CONSTRAINT FK_Resposta FOREIGN KEY(ID) REFERENCES Perguntas(ID)
);